version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.5-management
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lupulo_db
    ports:
      - 3306:3306